import PDFDocument from 'pdfkit';
import { Submission } from '@prisma/client';

export const generateReceiptPDF = (submission: Submission): PDFKit.PDFDocument => {
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 50, bottom: 50, left: 50, right: 50 },
  });

  // Header
  doc
    .fontSize(20)
    .font('Helvetica-Bold')
    .text('BUKTI PENGIRIMAN RESMI', { align: 'center' })
    .moveDown(0.5);

  doc
    .fontSize(14)
    .font('Helvetica')
    .text('Sayembara Desain Logo HUT ke-14', { align: 'center' })
    .text('Kabupaten Mamuju Tengah', { align: 'center' })
    .moveDown(2);

  // Divider
  doc
    .strokeColor('#00796B')
    .lineWidth(2)
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .stroke()
    .moveDown(1.5);

  // Content - Kode Registrasi (highlight)
  doc
    .fontSize(12)
    .font('Helvetica-Bold')
    .fillColor('#333333')
    .text('KODE REGISTRASI UNIK', { continued: false })
    .moveDown(0.3);

  doc
    .fontSize(18)
    .font('Helvetica-Bold')
    .fillColor('#00796B')
    .text(submission.submissionCode, { align: 'left' })
    .moveDown(1.5);

  // Data Peserta
  doc
    .fontSize(12)
    .font('Helvetica-Bold')
    .fillColor('#333333')
    .text('DATA PESERTA', { underline: true })
    .moveDown(0.5);

  const fields = [
    { label: 'Nama Lengkap', value: submission.name },
    { label: 'Email', value: submission.email },
    { label: 'Nomor WhatsApp', value: submission.whatsapp },
  ];

  fields.forEach((field) => {
    doc
      .fontSize(10)
      .font('Helvetica-Bold')
      .fillColor('#666666')
      .text(field.label + ':', { continued: true, width: 150 })
      .font('Helvetica')
      .fillColor('#000000')
      .text(' ' + field.value, { width: 350 });
    doc.moveDown(0.3);
  });

  doc.moveDown(1);

  // Data Karya
  doc
    .fontSize(12)
    .font('Helvetica-Bold')
    .fillColor('#333333')
    .text('DATA KARYA', { underline: true })
    .moveDown(0.5);

  doc
    .fontSize(10)
    .font('Helvetica-Bold')
    .fillColor('#666666')
    .text('Judul Karya:', { continued: true, width: 150 })
    .font('Helvetica')
    .fillColor('#000000')
    .text(' ' + submission.title, { width: 350 });
  doc.moveDown(0.3);

  doc
    .fontSize(10)
    .font('Helvetica-Bold')
    .fillColor('#666666')
    .text('Filosofi/Narasi:', { continued: false })
    .moveDown(0.2);

  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor('#000000')
    .text(submission.description, {
      width: 495,
      align: 'justify',
    });

  doc.moveDown(1);

  // Tanggal Submit
  const submittedDate = new Date(submission.createdAt).toLocaleDateString('id-ID', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZone: 'Asia/Makassar', // WITA
  });

  doc
    .fontSize(10)
    .font('Helvetica-Bold')
    .fillColor('#666666')
    .text('Tanggal Pengiriman:', { continued: true, width: 150 })
    .font('Helvetica')
    .fillColor('#000000')
    .text(' ' + submittedDate + ' WITA', { width: 350 });

  doc.moveDown(0.5);

  doc
    .fontSize(10)
    .font('Helvetica-Bold')
    .fillColor('#666666')
    .text('Status:', { continued: true, width: 150 })
    .font('Helvetica-Bold')
    .fillColor('#00796B')
    .text(' TERDAFTAR ✓', { width: 350 });

  doc.moveDown(2);

  // Divider
  doc
    .strokeColor('#CCCCCC')
    .lineWidth(1)
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .stroke()
    .moveDown(1);

  // Footer
  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor('#666666')
    .text('Panitia Sayembara Logo HUT ke-14 Kabupaten Mamuju Tengah', { align: 'center' })
    .text('Dinas Kepemudaan, Olahraga, Pariwisata dan Ekonomi Kreatif', { align: 'center' })
    .text('Dinas Komunikasi, Informatika, Statistik dan Persandian', { align: 'center' })
    .moveDown(0.5);

  doc
    .fontSize(8)
    .font('Helvetica-Oblique')
    .fillColor('#999999')
    .text('Dokumen ini sah tanpa tanda tangan (generated by system)', { align: 'center' })
    .moveDown(0.3);

  doc
    .fontSize(7)
    .fillColor('#CCCCCC')
    .text('Dicetak: ' + new Date().toLocaleString('id-ID', { timeZone: 'Asia/Makassar' }) + ' WITA', { align: 'center' });

  doc.end();

  return doc;
};
